# Generated by Django 3.2.2 on 2021-07-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voting_number_of_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_votings', to='voting.voting'),
        ),
    ]
